# Generate random task

import random

dictionary = {
    "nouns": ["policies",
              "workers",
              "cowards",
              "presents",
              "messages",
              "engines",
              "agreements",
              "candidates",
              "lakes",
              "agencies",
              "clients",
              "sectors",
              "samples",
              "oranges",
              "applications",
              "warnings",
              "administrations",
              "pollutions",
              "performances",
              "foundations"],
    "verbs": ["edit",
              "walk",
              "wash",
              "punch",
              "seat",
              "carve",
              "hang",
              "strangle",
              "ruin",
              "help",
              "charge",
              "axe",
              "support",
              "sponsor",
              "display",
              "separate",
              "devastate",
              "adjust",
              "entitle",
              "use"],
    "adjectives": ["soggy",
                   "zany",
                   "hospitable",
                   "luxurious",
                   "worthless",
                   "reflective",
                   "lonely",
                   "wealthy",
                   "strange",
                   "dark",
                   "former",
                   "pathetic",
                   "imaginary",
                   "gentle",
                   "slow",
                   "fast",
                   "flaky",
                   "tidy",
                   "melted",
                   "cumbersome"
                   ],
    "adverbs": ["Helplessly",
                "Annoyingly",
                "Noisily",
                "Scarily",
                "Yieldingly",
                "Helplessly",
                "Rapidly",
                "Silently",
                "Vivaciously",
                "Begrudgingly",
                "Thoroughly",
                "Defiantly",
                "Woefully",
                "Gladly",
                "Fondly",
                "Coolly",
                "Playfully",
                "Queerly",
                "Lively",
                "Abnormally"
                ]
}

def createRandomTask():
    n = random.randint(0,19)
    v = random.randint(0,19)
    a = random.randint(0,19)
    ad = random.randint(0,19)
    return f"{dictionary.get('adverbs')[ad]} {dictionary.get('verbs')[v]} {dictionary.get('adjectives')[a]} {dictionary.get('nouns')[n]}"

